### PR TITLE
babel-preset-env instead of babel-preset-es2015

### PR DESCRIPTION
**Pull request by keemor**
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

presets changed from es2015 to env

preact bumped to ^8.2.6 and moved from peerDependencies to devDependencies

### CODE REVIEW

**Comment by keemor** [comment]
Working example https://keemor.github.io/#/router

**Comment by jasonChen1982** [comment]
hello~ thanks for your PR. 😊😊

i want to know, is there a reason why move `preact ` from `peerDependencies` to `devDependencies`. 

in my opinion, `preact-highlight` was service the `preact app`, and the version should be specify by `preact app`, `preact-highlight` just need prompt developers should install `preact` according to their application. 

so i think `peerDependencies` was more suit for it

**Comment by keemor** [comment]
I thought preact is needed when building preact-highlight from sources 'cause right now it's not installed during npm install. I can change PR and leave preact in peerDependencies

**Comment by jasonChen1982** [comment]
`preact` was no needed when building

 building just dealing with theme style sheets and babel some es2015 syntax

**Pull request merged**
